"""种子项目数据:面向硕士申请者,聚焦欧陆/非中美英澳地区(项目核心场景)。

数据为人工整理(verified=True),官方源链接 sourceUrl 供人工校对与跳转。
字段对齐 frontend/src/types/index.ts 的 Program。仅收录典型英授硕士项目。
后续可由 programs_scraper.py 启发式抓取官方页扩充,再人工校对(verified=False)。
"""
from __future__ import annotations
from .schema import Program, Deadline, Requirements

# universityId 需与 universities.json 中的 id 一致(slug 规则:u_<name_slug>)
# 注意:不同榜单对同一校名称写法可能不同导致 slug 差异,需在 build 时做名称归一(见 normalize)。

SEED: list[Program] = [
    Program(
        id="ethz_msce_cs", universityId="u_eth_zurich",
        subject="Computer Science", dept="Department of Computer Science",
        program="Master in Computer Science",
        deadlines=[Deadline("Non-EU", "2025-12-15"), Deadline("EU", "2026-03-31")],
        materials=["Online application form", "Bachelor transcript", "CV", "Motivation letter",
                   "2 recommendation letters", "English proof (C1)"],
        requirements=Requirements(gpa=None, ielts="7.0", toefl="100"),
        sourceUrl="https://inf.ethz.ch/studies/master.html",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="ethz_msit_dpt", universityId="u_eth_zurich",
        subject="Information Technology", dept="D-ITET",
        program="Master in Information Technology",
        deadlines=[Deadline("Non-EU", "2025-12-15"), Deadline("EU", "2026-03-31")],
        materials=["Online application", "Transcript", "CV", "Motivation letter"],
        requirements=Requirements(ielts="7.0", toefl="100"),
        sourceUrl="https://www.ee.ethz.ch/studies/master.html",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="epfl_ms_cs", universityId="u_epfl",
        subject="Computer Science", dept="School of Computer and Communication Sciences",
        program="Master of Science in Computer Science",
        deadlines=[Deadline("Non-EU", "2025-12-15"), Deadline("EU", "2026-04-15")],
        materials=["Online application", "Bachelor transcript (translated)", "CV",
                   "Motivation letter", "2 references", "English certificate (C1)"],
        requirements=Requirements(ielts="7.0", toefl="100"),
        sourceUrl="https://www.epfl.ch/education/master/programs/computer-science/",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="tum_ms_informatics", universityId="u_technical_university_of_munich",
        subject="Computer Science", dept="Department of Informatics",
        program="Master in Informatics",
        deadlines=[Deadline("Non-EU", "2025-11-15"), Deadline("EU", "2026-01-15")],
        materials=["TUMonline application", "Transcript of records", "Degree certificate",
                   "CV", "Motivation letter", "English proof (B2/C1)"],
        requirements=Requirements(ielts="6.5", toefl="88"),
        sourceUrl="https://www.tum.de/en/studies/degree-programs/detail/informatics-master-of-science-msc",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="tum_ms_mechatronics", universityId="u_technical_university_of_munich",
        subject="Mechanical Engineering", dept="Department of Mechanical Engineering",
        program="Master in Mechatronics and Robotics",
        deadlines=[Deadline("Non-EU", "2025-11-15"), Deadline("EU", "2026-01-15")],
        materials=["TUMonline application", "Transcript", "CV", "Motivation letter",
                   "English proof (B2)"],
        requirements=Requirements(ielts="6.5", toefl="88"),
        sourceUrl="https://www.tum.de/en/studies/degree-programs/detail/mechatronics-robotic-and-biomechanical-engineering-master-of-science-msc",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="kth_ms_cs", universityId="u_kth_royal_institute_of_technology",
        subject="Computer Science", dept="School of Electrical Engineering and Computer Science",
        program="Master's programme in Computer Science",
        deadlines=[Deadline("Non-EU", "2026-01-15"), Deadline("EU", "2026-04-15")],
        materials=["Universityadmissions.se application", "Degree certificate",
                   "Transcript", "CV", "Letter of motivation", "English proof (B2/C1)"],
        requirements=Requirements(ielts="6.5", toefl="90"),
        sourceUrl="https://www.kth.se/en/studies/master/computer-science",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="kth_ms_machine_learning", universityId="u_kth_royal_institute_of_technology",
        subject="Machine Learning", dept="School of EECS",
        program="Master's programme in Machine Learning",
        deadlines=[Deadline("Non-EU", "2026-01-15"), Deadline("EU", "2026-04-15")],
        materials=["Universityadmissions.se application", "Transcript", "CV",
                   "Motivation letter", "English proof"],
        requirements=Requirements(ielts="6.5", toefl="90"),
        sourceUrl="https://www.kth.se/en/studies/master/machine-learning",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="tudelft_ms_cs", universityId="u_delft_university_of_technology",
        subject="Computer Science", dept="Faculty of EEMCS",
        program="MSc Computer Science",
        deadlines=[Deadline("Non-EU", "2025-12-01"), Deadline("EU", "2026-04-01")],
        materials=["TU Delft application portal", "Transcript", "Degree", "CV",
                   "Motivation letter", "2 reference letters", "English proof (C1)"],
        requirements=Requirements(ielts="7.0", toefl="100"),
        sourceUrl="https://www.tudelft.nl/onderwijs/opleidingen/masters/cs/msc-computer-science",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="kuleuven_ms_cs", universityId="u_ku_leuven",
        subject="Computer Science", dept="Faculty of Science",
        program="Master of Computer Science",
        deadlines=[Deadline("Non-EU", "2026-03-01"), Deadline("EU", "2026-06-01")],
        materials=["Online application", "Transcript", "Degree certificate", "CV",
                   "Motivation letter", "English proof (C1)"],
        requirements=Requirements(ielts="7.0", toefl="100"),
        sourceUrl="https://www.kuleuven.be/programme/master-computer-science",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="polimi_ms_cs", universityId="u_politecnico_di_milano",
        subject="Computer Science", dept="School of Industrial and Information Engineering",
        program="MSc in Computer Science and Engineering",
        deadlines=[Deadline("Non-EU (1st)", "2025-11-14"), Deadline("EU", "2026-04-30")],
        materials=["Online services application", "Transcript", "Bachelor degree",
                   "CV", "Motivation letter", "English certificate (B2/C1)"],
        requirements=Requirements(ielts="6.0", toefl="78"),
        sourceUrl="https://www.polimi.it/en/international-prospective-students/laurea-magistrale-equals-to-master-of-science",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="chalmers_ms_cs", universityId="u_chalmers_university_of_technology",
        subject="Computer Science", dept="Department of Computer Science and Engineering",
        program="MSc in Computer Science",
        deadlines=[Deadline("Non-EU", "2026-01-15"), Deadline("EU", "2026-04-15")],
        materials=["Universityadmissions.se application", "Transcript", "Degree",
                   "CV", "Motivation letter", "English proof (B2/C1)"],
        requirements=Requirements(ielts="6.5", toefl="90"),
        sourceUrl="https://www.chalmers.se/en/education/find-masters-programme/computer-science-msc/",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="aalto_ms_cs", universityId="u_aalto_university",
        subject="Computer Science", dept="School of Science",
        program="Master's Programme in Computer, Communication and Information Sciences",
        deadlines=[Deadline("Non-EU", "2026-01-08"), Deadline("EU", "2026-01-08")],
        materials=["Studyinfo.fi application", "Transcript", "Degree certificate",
                   "CV", "Motivation letter", "English proof (C1)"],
        requirements=Requirements(ielts="6.5", toefl="92"),
        sourceUrl="https://www.aalto.fi/en/study-options/masters-programme-in-computer-communication-and-information-sciences",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="sorbonne_ms_cs", universityId="u_sorbonne_university",
        subject="Computer Science", dept="Faculty of Science and Engineering",
        program="Master in Computer Science",
        deadlines=[Deadline("Non-EU", "2026-01-31"), Deadline("EU", "2026-05-15")],
        materials=["Mon Master / online application", "Transcript", "Degree", "CV",
                   "Motivation letter", "English/French proof"],
        requirements=Requirements(ielts="6.5", toefl="85"),
        sourceUrl="https://www.sciences.sorbonne-universite.fr/formation/masters/master-informatique/",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="dtu_ms_cs", universityId="u_technical_university_of_denmark",
        subject="Computer Science", dept="Department of Applied Mathematics and Computer Science",
        program="MSc in Computer Science",
        deadlines=[Deadline("Non-EU", "2026-01-15"), Deadline("EU", "2026-03-15")],
        materials=["Apply via DTU portal", "Transcript", "Bachelor degree", "CV",
                   "Motivation letter", "English proof (C1)"],
        requirements=Requirements(ielts="6.5", toefl="85"),
        sourceUrl="https://www.dtu.dk/english/education/graduate/msc-programmes/computer-science",
        verified=True, updatedAt=Program.now(),
    ),
    Program(
        id="twhd_ms_cs", universityId="u_tu_dresden",
        subject="Computer Science", dept="Faculty of Computer Science",
        program="Master in Computer Science",
        deadlines=[Deadline("Non-EU", "2026-04-30"), Deadline("EU", "2026-09-30")],
        materials=["TUMonline/ARIEL application", "Transcript", "Degree", "CV",
                   "Motivation letter", "English proof (B2)"],
        requirements=Requirements(ielts="6.5", toefl="88"),
        sourceUrl="https://tu-dresden.de/fakultaet/forschung/studienangebot/studiengang/informatik-ma",
        verified=True, updatedAt=Program.now(),
    ),
]


def seed_programs() -> list[Program]:
    return [Program(**{**p.__dict__, "requirements": p.requirements, "deadlines": p.deadlines}) for p in SEED]
